### PR TITLE
Compare message by key.value

### LINKED ISSUE #46: False error regarding missing template messages
## Expected Behavior
When using a template and the message translation is present in the file, there should be no warnings that the message is not provided.

## Actual Behavior
A warning is issued about a missing template.

## Steps to Reproduce the Problem
1. Create files below
2. Observe the error

en.arb
```json
{
    "@@locale": "en",
    "hello": "Hello",
    "@hello": {
        "description": "Say hello"
    }
}
```

en_UK.arb
```json
{
    "@@locale": "en_UK",
    "@@x-template": "en.arb",
    "hello": "Hello"
}
```

There is a warning at `en_UK.arb` that translation for `hello` isn't provided even though it is.

## Specifications
- Version: `0.0.12`
- Platform: `macOS, 14.3.1`

### PR DESCRIPTION
**Pull request by kzrnm**
Fixes #46

- [x] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

File: src/diagnose.ts [hunk 1]
```diff
@@ -211,4 +205,16 @@ export class Diagnostics {
...
+	}
+	let missing: Key[] = [];
+	const messageKeys: Set<string> = new Set<string>(messageList.messageEntries.map(m => m.key.value));
+	for (const entry of templateMessageList.messageEntries) {
+		if (!messageKeys.has(entry.key.value)) {
+			missing.push(entry.key);
+		}
+	}
+	return missing;
+}
```
Comment (mosuem) [inline src/diagnose.ts:220]: Nit: missing newlines on this and other files

**Review by mosuem — APPROVED** [review]

**Comment by mosuem** [comment]
Thanks a lot!
