### PR TITLE
Fix reference

### LINKED ISSUE #43: Ignore placeholder warning if template-arb-file is set
## Expected Behavior
I would like to request the addition of a feature that allows developers to ignore 'specific linter rules' during arb analysis like "placeholder".

## Actual Behavior
Currently, there is no way to ignore rules like 'Placeholder X not defined in the message metadata'. My 'template-arb-file' is set to my EN file and I should not need to duplicate my placeholder.

## Specifications
- Version of the linter or code analysis tool: v0.0.11
- Platform: macOS

### PR DESCRIPTION
**Pull request by mosuem**
Fixes #43.

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

File: src/diagnose.ts [hunk 1]
```diff
@@ -76,7 +108,7 @@ export class Diagnostics {
 					DiagnosticCode.invalidKey,
 				);
 			} else {
-				if (metadata === null && isReference) {
+				if (metadata === null && (isReference === undefined || isReference)) {
```
Comment (DanTup) [inline src/diagnose.ts:111]: `isReference !== false` maybe a little more readable?

File: README.md [hunk 2]
```diff
@@ -44,4 +44,9 @@ An extension to help you in editing .arb files, used for localization of applica
 Escaping quotes can be turned off by including a `l10n.yaml` file with the line:
 ```yaml
 use-escaping: false
+```
+
+To set a reference file, set `"@@x-reference": true` element in your `arb` file, or set a file to be the reference in the `l10n.yaml` using:
```
Comment (DanTup) [inline README.md:49]: What does setting this to `true` mean? Where does the template/reference file come from if the value is only `true`?

File: src/test/testarb_2.arb [hunk 3]
```diff
@@ -0,0 +1,11 @@
+{
+    "@@locale": "en",
+    "@@x-reference": false,
```
Comment (DanTup) [inline src/test/testarb_2.arb:3]: Why is this false? Is it because the test overrides it (by simulating it being set in the yaml file)? If so, is this key necessary?

Should there be a test with is set to `true`?

**Comment by DanTup** [comment]
(Sorry for the delay, a GitHub issue resulted in my emailing routing being reset and notifications going to the wrong mailbox 🙃)

File: README.md (hunk 2 above)
Comment (mosuem) [reply README.md:49]: Yeah it makes more sense for this also to be a file path to the template file, or empty if this is a template itself. And to use one of the two words consistently :D

File: src/extension.ts [hunk 4]
```diff
@@ -105,9 +105,33 @@ export async function activate(context: vscode.ExtensionContext) {
...
+				let templatePath: string;
+				if (templatePathFromOptions) {
+					if (path.isAbsolute(templatePathFromOptions!)) {
+						templatePath = templatePathFromOptions!;
+					} else {
+						templatePath = path.join(path.dirname(l10nYamlPath!), templatePathFromOptions);
+					}
+				} else {
+					if (path.isAbsolute(templatePathFromFile!)) {
+						templatePath = templatePathFromFile!;
```
Comment (DanTup) [inline src/extension.ts:122]: I think this means the path from options will be used in preference to the one in the file - should it be the other way around? (eg. you can set a global one in options, but override it per-file)?

**Review by DanTup — APPROVED** [review]

File: src/extension.ts (hunk 4 above)
Comment (mosuem) [reply src/extension.ts:122]: That was my thinking, but all these `templateFile...` variables got me confused :laughing:
